version: '3'
services:
  mongo-express:
    image: 'mongo-express:latest'
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: suhasumesh
      ME_CONFIG_MONGODB_ADMINPASSWORD: 123
      ME_CONFIG_MONGODB_URL: mongodb+srv://suhasumesh:123@inotebook.hzc53hm.mongodb.net/note
  server:
    build:
      context: ./backend
      dockerfile: Dockerfile
    # image: 
    # container_name: myapp-node-server
    # command: /usr/src/app/node_modules/.bin/nodemon server.js
    volumes:
      - /app/node_modules
      - ./backend:/app
    ports:
      - "5000:5000"
    depends_on:
      - mongo
    env_file: ./backend/.env
    environment:
      - NODE_ENV=development
    networks:
      - app-network
  mongo:
    image: mongo
    volumes:
      - data-volume:/data/db
    ports:
      - "27017:27017"
    networks:
      - app-network
  client:
    build:
      context: ./client
      dockerfile: Dockerfile
    image: suhasumesh/inotebook_client
    container_name: suhasumeshclient
    command: npm start
    volumes:
      - ./client/:/app
      - /app/node_modules
    depends_on:
      - server
    ports:
      - "3000:3000"
    networks:
      - app-network

networks:
    app-network:
        driver: bridge

volumes:
    data-volume:
    node_modules:
    web-root:
      driver: local